apiVersion: v1
kind: Service
metadata:
  name: kidsbank-service
spec:
  selector:
    app: kidsbank
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kidsbank-deployment
  labels:
    app: kidsbank
spec:
  selector:
    matchLabels:
      app: kidsbank
  replicas: 1
  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: kidsbank
    spec:
      containers:
      - name: kidsbank
        image: agapelee/kidsbank:latest
        ports:
        - containerPort: 9000
