apiVersion: v1
kind: Secret
metadata:
  name: mysqldb-secrets
type: Opaque
data:
  ROOT_PASSWORD: cm9vdA==  #root
  DATABASE_NAME: dGVzdGRi  #testdb
  USERNAME: YWdhcGVsZWU=   #agapelee
  PASSWORD: MDgwOQ==       #0809
