---
- name: Deploy kidsbank webapp 
  hosts: kubernetes1
  become: yes
  tasks:
         - name: Create the web-app deployments and services
           command: 
              cmd: kubectl apply -f /home/agape03/k8s-config/
           environment:
              KUBECONFIG: /home/agape03/.kube/config


         - name: Update deployment with new pods if image updated
           command:
              cmd: kubectl rollout restart deployment.apps/kidsbank-deployment
           environment:
              KUBECONFIG: /home/agape03/.kube/config
         
 #       - name: Remove containerized docker image to prevent stack in the storage
 #         command:
 #            cmd: docker rmi agapelee/kidsbank:latest

