---
- name: Deploy kidsbank webapp 
  hosts: kubernetes1
  become: yes
  tasks:
         - name: Pull kidsbank docker image
           command:
              cmd: docker pull agapelee/kidsbanktest:latest

         - name: Copy k8s files to home directory
           copy:
              src: /var/www/html/kidsbank-spefinal/k8s-config
              dest: /home/agape03
              mode: '0775'

         - name: Create web-app deployments and services.
           command: 
              cmd: kubectl apply -f /home/agape03/k8s-config/


